### ISSUE TITLE
Exception on local network gateway objects.

### ISSUE THREAD

**Issue by KyleTheAutomator** [andyt530/py-az2tf#14]
While running "./az2tf.sh -s xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -v yes".  I receive the following exception.

```
# azurerm_local_network_gateway 4
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 326, in <module>
    azurerm_local_network_gateway.azurerm_local_network_gateway(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/home/kyle/py-az2tf/scripts/azurerm_local_network_gateway.py", line 70, in azurerm_local_network_gateway
    fr.write('\t\t asn = "' + asn + '"\n')
TypeError: cannot concatenate 'str' and 'int' objects
TypeError: cannot concatenate 'str' and 'int' objects
Error in az2tf.py
```

**Comment by andyt530** [comment]
Hi,

Just posted a fix - please give it another go.

Thanks

**Comment by KyleTheAutomator** [comment]
Different error now, looks like a problem in a dict.  Not sure if it's related.

```
./az2tf.sh -s "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -v yes

Subscription ID = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Azure Resource Group Filter =
Terraform Resource Type Filter =
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no

python2.7 ../../scripts/az2tf.py -s xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 2>&1 | tee -a import.log
Get Access Token from CLI
Subscription: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Found subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx proceeding ...
# azurerm_resource_group 28
# azurerm_management_lock 0
# azurerm_user_assigned_identity 0
# azurerm_availability_set 0
# azurerm_route_table 42
# azurerm_application_security_group 0
# azurerm_network_security_group 43
# azurerm_virtual_network 1
# azurerm_subnet 1
# azurerm_virtual_network_peering 1
# azurerm_key_vault 1
# azurerm_managed_disk 6
# azurerm_storage_account 29
# azurerm_public_ip 5
# azurerm_traffic_manager_profile 0
# azurerm_traffic_manager_endpoint 0
# azurerm_network_interface 5
# azurerm_dns_zone 29
# azurerm_lb 0
# azurerm_lb_nat_rule 0
# azurerm_lb_nat_pool 0
# azurerm_lb_backend_address_pool 0
# azurerm_lb_probe 0
# azurerm_lb_rule 0
# azurerm_application_gateway 0
# azurerm_local_network_gateway 4
# azurerm_virtual_network_gateway 1
# azurerm_virtual_network_gateway_connection 4
# azurerm_express_route_circuit 0
# azurerm_express_route_circuit_authorization 0
# azurerm_express_route_circuit_peering 0
# azurerm_container_registry 1
# azurerm_kubernetes_cluster 0
# azurerm_recovery_services_vault 1
# azurerm_virtual_machine 5
# azurerm_virtual_machine_extension 5
# azurerm_virtual_machine_scale_set 0
# azurerm_automation_account 1
# azurerm_log_analytics_workspace 3
# azurerm_log_analytics_solution 7
# azurerm_image 0
# azurerm_shared_image_gallery 0
# azurerm_snapshot 0
# azurerm_network_watcher 1
# azurerm_cosmosdb_account 0
# azurerm_servicebus_namespace 0
# azurerm_servicebus_queue 0
# azurerm_sql_server 2
# azurerm_sql_database 2
# azurerm_databricks_workspace 0
# azurerm_app_service_plan 3
# azurerm_app_service 4
# azurerm_function_app 4
# azurerm_logic_app_workflow 0
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 387, in <module>
    azurerm_api_management.azurerm_api_management(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/home/kyle/py-az2tf/scripts/azurerm_api_management.py", line 13, in azurerm_api_management
    azr= r.json()["value"]
KeyError: 'value'
KeyError: 'value'
Error in az2tf.py
```

**Comment by andyt530** [comment]
and another workaround ..... please try again.
