### ISSUE TITLE
Validation error related to OmsAgentForLinux

### ISSUE THREAD

**Issue by bernardmaltais** [andyt530/py-az2tf#16]
Trying the quickstart and ran in one of those error that you requested to be logged. I hope this will help you:

```
root@14042f86dee0:~/py-az2tf# ./az2tf.sh -s 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e -v yes

Subscription ID = 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e
Azure Resource Group Filter =
Terraform Resource Type Filter =
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no

python2.7 ../../scripts/az2tf.py -s 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e 2>&1 | tee -a import.log
Get Access Token from CLI
Subscription: 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e
Found subscription 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e proceeding ...
# azurerm_resource_group 7
# azurerm_management_lock 0
# azurerm_user_assigned_identity 0
# azurerm_availability_set 0
# azurerm_route_table 0
# azurerm_application_security_group 0
# azurerm_network_security_group 0
# azurerm_virtual_network 4
# azurerm_subnet 4
# azurerm_virtual_network_peering 4
# azurerm_key_vault 0
# azurerm_managed_disk 3
# azurerm_storage_account 0
# azurerm_public_ip 0
# azurerm_traffic_manager_profile 0
# azurerm_traffic_manager_endpoint 0
# azurerm_network_interface 3
# azurerm_dns_zone 0
# azurerm_lb 0
# azurerm_lb_nat_rule 0
# azurerm_lb_nat_pool 0
# azurerm_lb_backend_address_pool 0
# azurerm_lb_probe 0
# azurerm_lb_rule 0
# azurerm_application_gateway 0
# azurerm_local_network_gateway 0
# azurerm_virtual_network_gateway 0
# azurerm_virtual_network_gateway_connection 0
# azurerm_express_route_circuit 0
# azurerm_express_route_circuit_authorization 0
# azurerm_express_route_circuit_peering 0
# azurerm_container_registry 0
# azurerm_kubernetes_cluster 0
# azurerm_recovery_services_vault 0
# azurerm_virtual_machine 3
# azurerm_virtual_machine_extension 3
# azurerm_virtual_machine_scale_set 0
# azurerm_automation_account 0
# azurerm_log_analytics_workspace 0
# azurerm_log_analytics_solution 0
# azurerm_image 0
# azurerm_shared_image_gallery 0
# azurerm_snapshot 0
# azurerm_network_watcher 1
# azurerm_cosmosdb_account 0
# azurerm_sql_server 0
# azurerm_sql_database 0
# azurerm_databricks_workspace 0
# azurerm_app_service_plan 0
# azurerm_app_service 0
# azurerm_function_app 0
# azurerm_logic_app_workflow 0
# azurerm_api_management 0
# azurerm_monitor_autoscale_setting 0
terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /root/py-az2tf/generated/tf.2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/azurerm_virtual_machine_extension.hub-vnet-rg__hub-vm__OmsAgentForLinux.tf: At 11:12: Unknown token: 11:12 IDENT jsonencode


Error: Error parsing /root/py-az2tf/generated/tf.2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/azurerm_virtual_machine_extension.hub-vnet-rg__hub-vm__OmsAgentForLinux.tf: At 11:12: Unknown token: 11:12 IDENT jsonencode
Error with terraform init
```

**Comment by andyt530** [comment]
Hi,

Could you post the contents of the file azurerm_virtual_machine_extension.hub-vnet-rg__hub-vm__OmsAgentForLinux.tf  here please

**Comment by bernardmaltais** [comment]
Hello Andy,

Tried to re-create the issue but things must have changed in the subscription. It is no longer tripping on the  OmsAgentForLinux. I lost the tf file as I was running from a docker container that was configured to deleted itself on exit. Sorry.

**Comment by bernardmaltais** [comment]
On the other hand I am now running in a different issue:

```
root@7b6f484f3559:~/py-az2tf# ./az2tf.sh -s 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e -v yes

Subscription ID = 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e
Azure Resource Group Filter =
Terraform Resource Type Filter =
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no

python2.7 ../../scripts/az2tf.py -s 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e 2>&1 | tee -a import.log
Get Access Token from CLI
Subscription: 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e
Found subscription 2de839a0-37f9-4163-a32a-e1bdb8d6eb7e proceeding ...
# azurerm_resource_group 19
# azurerm_management_lock 0
# azurerm_user_assigned_identity 0
# azurerm_availability_set 0
# azurerm_route_table 5
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 284, in <module>
    azurerm_route_table.azurerm_route_table(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/root/py-az2tf/scripts/azurerm_route_table.py", line 26, in azurerm_route_table
    loc=azr[i]["location"]
KeyError: 'location'
KeyError: 'location'
Error in az2tf.py
```

I have started to deploy some resources in the subscription using terraform and if I leave those resources in the subscription py-az2tf is giving the error above.

If a terraform destroy those resources it work fine.

If I look in the subscription there is only 3 route-tables but somehow py-az2tf report 5 as can be seen in the log above... look like why it is complaining of the two location KeyError.

**Comment by bmaltais** [comment]
In case this help... I added a "print azr" after line 11 in azure-route-table.py to see what was being parsed and got this:

```
[{u'properties': {u'routes': [{u'properties': {u'addressPrefix': u'0.0.0.0/0', u'nextHopType': u'Internet', u'provisioningState': u'Succeeded'}, u'etag': u'W/"f57ee8ff-bd89-4aca-99bc-77cea5e52edc"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'FirewallDefaultRoute', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/Demo-Infra-NetCore-RG/providers/Microsoft.Network/routeTables/AzureFirewall_Demo-Infra-NetCore-VNET-msfirewall/routes/FirewallDefaultRoute'}], u'resourceGuid': u'01394bd3-d4fb-4dc0-8eed-fa4235b5c6fc', u'disableBgpRoutePropagation': False, u'provisioningState': u'Succeeded'}, u'etag': u'W/"f57ee8ff-bd89-4aca-99bc-77cea5e52edc"', u'type': u'Microsoft.Network/routeTables', u'name': u'AzureFirewall_Demo-Infra-NetCore-VNET-msfirewall', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/Demo-Infra-NetCore-RG/providers/Microsoft.Network/routeTables/AzureFirewall_Demo-Infra-NetCore-VNET-msfirewall'}, {u'properties': {u'routes': [{u'properties': {u'addressPrefix': u'0.0.0.0/0', u'nextHopType': u'Internet', u'provisioningState': u'Succeeded'}, u'etag': u'W/"90280ce0-cadd-43b1-82a0-7e457c0704e9"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'FirewallDefaultRoute', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/DND-Infra-NetCore-RG/providers/Microsoft.Network/routeTables/AzureFirewall_DND-Infra-NetCore-VNET-msfirewall/routes/FirewallDefaultRoute'}], u'resourceGuid': u'5a09ff50-5102-4406-84c9-6ad7f8e66c8e', u'disableBgpRoutePropagation': False, u'provisioningState': u'Succeeded'}, u'etag': u'W/"90280ce0-cadd-43b1-82a0-7e457c0704e9"', u'type': u'Microsoft.Network/routeTables', u'name': u'AzureFirewall_DND-Infra-NetCore-VNET-msfirewall', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/DND-Infra-NetCore-RG/providers/Microsoft.Network/routeTables/AzureFirewall_DND-Infra-NetCore-VNET-msfirewall'}, {u'name': u'PwPT-MGMT-APP-RT', u'tags': {u'Organizations': u'PwP0-CCC-E&O', u'DeploymentVersion': u'2018-12-14-01', u'Classification': u'Unclassified', u'Enviroment': u'Sandbox', u'CostCenter': u'PwP0-EA', u'Owner': u'cloudteam@tpsgc-pwgsc.gc.ca'}, u'properties': {u'routes': [{u'properties': {u'addressPrefix': u'100.96.122.0/24', u'nextHopType': u'VnetLocal', u'provisioningState': u'Succeeded'}, u'etag': u'W/"99c971ed-86a1-480e-b0f5-d9069b025cb8"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'local-Subnet', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-APP-RT/routes/local-Subnet'}, {u'properties': {u'addressPrefix': u'100.96.120.0/21', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"99c971ed-86a1-480e-b0f5-d9069b025cb8"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-MGMT-VNET', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-APP-RT/routes/PwPT-MGMT-VNET'}, {u'properties': {u'addressPrefix': u'100.96.116.64/27', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"99c971ed-86a1-480e-b0f5-d9069b025cb8"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-Management', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-APP-RT/routes/PwPT-Management'}, {u'properties': {u'addressPrefix': u'100.96.112.0/21', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"99c971ed-86a1-480e-b0f5-d9069b025cb8"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-Core-VNET', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-APP-RT/routes/PwPT-Core-VNET'}, {u'properties': {u'addressPrefix': u'0.0.0.0/0', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"99c971ed-86a1-480e-b0f5-d9069b025cb8"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'default', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-APP-RT/routes/default'}], u'subnets': [{u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/virtualNetworks/PwPT-Core-NetMGMT-VNET/subnets/PwPT-MGMT-APP'}], u'resourceGuid': u'af6d05cd-61ad-45c9-8f7d-8418fa58a350', u'disableBgpRoutePropagation': False, u'provisioningState': u'Succeeded'}, u'etag': u'W/"99c971ed-86a1-480e-b0f5-d9069b025cb8"', u'location': u'canadacentral', u'type': u'Microsoft.Network/routeTables', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-APP-RT'}, {u'name': u'PwPT-MGMT-DB-RT', u'tags': {u'Organizations': u'PwP0-CCC-E&O', u'DeploymentVersion': u'2018-12-14-01', u'Classification': u'Unclassified', u'Enviroment': u'Sandbox', u'CostCenter': u'PwP0-EA', u'Owner': u'cloudteam@tpsgc-pwgsc.gc.ca'}, u'properties': {u'routes': [{u'properties': {u'addressPrefix': u'100.96.124.0/24', u'nextHopType': u'VnetLocal', u'provisioningState': u'Succeeded'}, u'etag': u'W/"444e7fd8-0cd9-4dbe-a9df-c8edbdf9943f"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'local-Subnet', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-DB-RT/routes/local-Subnet'}, {u'properties': {u'addressPrefix': u'100.96.120.0/21', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"444e7fd8-0cd9-4dbe-a9df-c8edbdf9943f"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-MGMT-VNET', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-DB-RT/routes/PwPT-MGMT-VNET'}, {u'properties': {u'addressPrefix': u'100.96.116.64/27', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"444e7fd8-0cd9-4dbe-a9df-c8edbdf9943f"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-Management', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-DB-RT/routes/PwPT-Management'}, {u'properties': {u'addressPrefix': u'100.96.112.0/21', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"444e7fd8-0cd9-4dbe-a9df-c8edbdf9943f"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-Core-VNET', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-DB-RT/routes/PwPT-Core-VNET'}, {u'properties': {u'addressPrefix': u'0.0.0.0/0', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"444e7fd8-0cd9-4dbe-a9df-c8edbdf9943f"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'default', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-DB-RT/routes/default'}], u'subnets': [{u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/virtualNetworks/PwPT-Core-NetMGMT-VNET/subnets/PwPT-MGMT-DB'}], u'resourceGuid': u'a4eb6329-5c1c-4714-8d9c-8c8163673ab2', u'disableBgpRoutePropagation': False, u'provisioningState': u'Succeeded'}, u'etag': u'W/"444e7fd8-0cd9-4dbe-a9df-c8edbdf9943f"', u'location': u'canadacentral', u'type': u'Microsoft.Network/routeTables', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-DB-RT'}, {u'name': u'PwPT-MGMT-PAZ-RT', u'tags': {u'Organizations': u'PwP0-CCC-E&O', u'DeploymentVersion': u'2018-12-14-01', u'Classification': u'Unclassified', u'Enviroment': u'Sandbox', u'CostCenter': u'PwP0-EA', u'Owner': u'cloudteam@tpsgc-pwgsc.gc.ca'}, u'properties': {u'routes': [{u'properties': {u'addressPrefix': u'100.96.120.0/24', u'nextHopType': u'VnetLocal', u'provisioningState': u'Succeeded'}, u'etag': u'W/"340298ac-5c42-4482-98e3-f0ac838f4f2d"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'local-Subnet', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-PAZ-RT/routes/local-Subnet'}, {u'properties': {u'addressPrefix': u'100.96.120.0/21', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"340298ac-5c42-4482-98e3-f0ac838f4f2d"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-MGMT-VNET', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-PAZ-RT/routes/PwPT-MGMT-VNET'}, {u'properties': {u'addressPrefix': u'100.96.116.64/27', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"340298ac-5c42-4482-98e3-f0ac838f4f2d"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-Management', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-PAZ-RT/routes/PwPT-Management'}, {u'properties': {u'addressPrefix': u'100.96.112.0/21', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"340298ac-5c42-4482-98e3-f0ac838f4f2d"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'PwPT-Core-VNET', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-PAZ-RT/routes/PwPT-Core-VNET'}, {u'properties': {u'addressPrefix': u'0.0.0.0/0', u'nextHopType': u'VirtualAppliance', u'nextHopIpAddress': u'100.96.116.4', u'provisioningState': u'Succeeded'}, u'etag': u'W/"340298ac-5c42-4482-98e3-f0ac838f4f2d"', u'type': u'Microsoft.Network/routeTables/routes', u'name': u'default', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-PAZ-RT/routes/default'}], u'subnets': [{u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/virtualNetworks/PwPT-Core-NetMGMT-VNET/subnets/PwPT-MGMT-PAZ'}], u'resourceGuid': u'3d305560-9c79-4881-b03e-49746eda3de7', u'disableBgpRoutePropagation': False, u'provisioningState': u'Succeeded'}, u'etag': u'W/"340298ac-5c42-4482-98e3-f0ac838f4f2d"', u'location': u'canadacentral', u'type': u'Microsoft.Network/routeTables', u'id': u'/subscriptions/2de839a0-37f9-4163-a32a-e1bdb8d6eb7e/resourceGroups/PwPT-Core-NetMGMT-RG/providers/Microsoft.Network/routeTables/PwPT-MGMT-PAZ-RT'}]
```

Look like there is only 3 location as expected. Not sure why it is reporting 5 and tripping on those 2 extr.

**Comment by bmaltais** [comment]
I appear to have worked around the issue by wrapping the offending code in a try: statement:

````
try:
                name = azr[i]["name"]
                loc = azr[i]["location"]
                id = azr[i]["id"]
                rg = id.split("/")[4].replace(".", "-").lower()
                rgs = id.split("/")[4]
            except KeyError:
                    continue
````

Still report 5 routes but at least it now outputs the actual 3 routes and continue.

**Comment by andyt530** [comment]
That is strange - the REST call is returning only partial information for two of your routes. (the ones without location populated). It shouldn't.

The workaround is good for now while I try and reproduce/figure it out.

**Comment by bernardmaltais** [comment]
Here is a copy of the terraform deployment that is causing the issue on my side. Maybe it will help you reproduce the issue: https://1drv.ms/f/s!AroDHk41Y7i-g8gsl2gmapBj6WGMGw

It was created by weaving together outputs from py-az2tf and making some adjustments to make it use more functions and variables.

**Comment by andyt530** [comment]
that all worked this side - I wonder if you had some routes left over in a partially deleted Resource Group ?

**Comment by bernardmaltais** [comment]
Must be an Azure bug then. Strange that it reports extra empty route-tables entry but I can't see those in the Portal either. Heh. Not the 1st not the last Azure bug.

Or is it possible my docker container is the source? Perhaps some of the version of python resources are causing the issue? If you try to run the same terraform command using the docker image does it also work?
