### ISSUE TITLE
azurerm_express_route_circuit_peering  error "UnboundLocalError: local variable 'fr' referenced before assignment"

### ISSUE THREAD

**Issue by asubmani** [andyt530/py-az2tf#31]
az cli 2.0.74
Terraform 0.12.9
OS: WSL2 - Ubuntu 18.04
command used: `./az2tf.sh -s 8cfbd600-1193-40e4-8a27-xxxxxxxxx -d yes -f yes -v yes`

Description: The script fails when it reaches the express route stage. 
```# File generated by py-az2tf see: https://github.com/andyt530/py-az2tf

# azurerm_express_route_circuit_peering 1
{
    "sku": {
        "tier": "Premium",
        "name": "Premium_MeteredData",
        "family": "MeteredData"
    },
    "name": "xx_to_Azure_EAST_PROD2",
    "id": "/subscriptions/oood600-1193-40e4-8a27-xxxxxxxx/resourceGroups/ExpressRouteUSeast/providers/Microsoft.Network/expressRouteCircuits/xto_Azure_EAST_PROD2",
    "etag": "W/\"d53cc9b8-7434-49cf-8aa4-eac50404856f\"",
    "location": "eastus",
    "type": "Microsoft.Network/expressRouteCircuits",
    "properties": {
        "provisioningState": "Succeeded",
        "circuitProvisioningState": "Enabled",
        "authorizations": [],
        "serviceProviderProvisioningState": "NotProvisioned",
        "gatewayManagerEtag": "",
        "serviceProviderProperties": {
            "serviceProviderName": "Verizon",
            "bandwidthInMbps": 100,
            "peeringLocation": "Washington DC"
        },
        "allowClassicOperations": false,
        "serviceKey": "xxxxxxx-afb8-7ffb9b290723",
        "peerings": [],
        "resourceGuid": "xxxxxxxxxxxx-a98a-d31d3413615b"
    }
}
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 345, in <module>
    azurerm_express_route_circuit_peering.azurerm_express_route_circuit_peering(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/mnt/c/github/py-az2tf/scripts/azurerm_express_route_circuit_peering.py", line 91, in azurerm_express_route_circuit_peering          fr.write('}\n')
UnboundLocalError: local variable 'fr' referenced before assignment
UnboundLocalError: local variable 'fr' referenced before assignment
Error in az2tf.py
```

**Comment by andyt530** [comment]
posted an attempted fix for this

**Comment by asubmani** [comment]
> posted an attempted fix for this

Thanks for the quick follow up. I am still getting the error (diff line numbers).
```python
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 345, in <module>
    azurerm_express_route_circuit_peering.azurerm_express_route_circuit_peering(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/mnt/c/github/py-az2tf/scripts/azurerm_express_route_circuit_peering.py", line 95, in azurerm_express_route_circuit_peering
    with open(rfilename) as f:
UnboundLocalError: local variable 'rfilename' referenced before assignment
UnboundLocalError: local variable 'rfilename' referenced before assignment
Error in az2tf.py
```

**Comment by andyt530** [comment]
Thanks - another fix attempt posted.

**Comment by asubmani** [comment]
Thank you. This fixed the issue. Closing the "issue"

> Thanks - another fix attempt posted.
