### ISSUE TITLE
Vnet Gateway with SKU: Basic returns null

### ISSUE THREAD

**Issue by asubmani** [andyt530/py-az2tf#32]
Az cli version  = 2.0.74 (installed on WSL2/Ubuntu)
Terraform = 0.12.9 (linux)
OS = WSL2 on Windows 10 (Ubuntu 18.04)

## Error enumerating vnet gateways of that has a sku= 'basic'

```python
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 337, in <module>
    azurerm_virtual_network_gateway.azurerm_virtual_network_gateway(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/mnt/c/github/py-az2tf/scripts/azurerm_virtual_network_gateway.py", line 53, in azurerm_virtual_network_gateway          sku=azr[i]["properties"]["sku"]["name"]
KeyError: 'sku'
KeyError: 'sku'
Error in az2tf.py
```

## Potential root cause

The `azr` variable in the file `azurerm_virtual_network_gateway.py` shows no sub-property under 'properties' for the gateway that has a basic SKU.

## Troubleshooting

Confirmed that az cli returns the SKU with value Basic

`az network vnet-gateway show -n gw-Resource-EastUS2 -g resourcegroupname`

this returns

```json
 "resourceGuid": "447f57f0-e5bd-4b1e-ae16-2716a32a542e",
  "sku": {
    "capacity": 2,
    "name": "Basic",
    "tier": "Basic"
  },
```

Tried changing the API version to : `params = {'api-version': '2019-07-01'}` Same issue persists.

Since sku is `null` the below gives a `keyError`

```python
azr[2]["properties"]["sku"]
```
This could be related to Python SDK for Azure or the `requests` module in Python.

**Comment by andyt530** [comment]
Could you post the debug output please:
./az2tf.sh -s yoursub -d yes -v yes -r virtual_network_gateway -g resourcegroupname

**Comment by asubmani** [comment]
> Could you post the debug output please:
> ./az2tf.sh -s yoursub -d yes -v yes -r virtual_network_gateway -g resourcegroupname

Here it is
```json
Subscription ID = xxxxxxxx-yyyyyy-hghgh-qqwqer
Azure Resource Group Filter = myResourceGroup
Terraform Resource Type Filter = virtual_network_gateway
Get Subscription Policies & RBAC = no
Extract Key Vault Secrets to .tf files (insecure) = no
Fast Forward = no
Validate Only = yes
Debug = no
 
python2.7 ../../scripts/az2tf.py -s xxxxxxxx-yyyyyy-hghgh-qqwqer -g myResourceGroup -r virtual_network_gateway -d yes 2>&1 | tee -a import.log
resource group=myResourceGroup
resource filter=virtual_network_gateway
Debug=True
Get Access Token from CLI
Subscription: xxxxxxxx-yyyyyy-hghgh-qqwqer
Found subscription xxxxxxxx-yyyyyy-hghgh-qqwqer proceeding ...
Found Resource GroupmyResourceGroup
# azurerm_virtual_network_gateway 3
{
    "name": "zz-gw-Resource-EastUS2",
    "id": "/subscriptions/xxxxxxxx-yyyyyy-hghgh-qqwqer/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworkGateways/zz-gw-Resource-EastUS2",
    "etag": "W/\"9c8e6845-d88b-4dd1-af96-708c3d55e438\"",
    "location": "eastus2",
    "type": "Microsoft.Network/virtualNetworkGateways",
    "properties": {
        "vpnClientConfiguration": {
            "vpnClientRootCertificates": [],
            "vpnClientIpsecPolicies": [],
            "vpnClientProtocols": [],
            "vpnClientRevokedCertificates": []
        },
        "vpnType": "RouteBased",
        "gatewayType": "ExpressRoute",
        "activeActive": false,
        "enableBgp": false,
        "provisioningState": "Succeeded",
        "vpnGatewayGeneration": "None",
        "ipConfigurations": [
            {
                "properties": {
                    "subnet": {
                        "id": "/subscriptions/xxxxxxxx-yyyyyy-hghgh-qqwqer/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/Resource-EastUS2/subnets/GatewaySubnet"
                    },
                    "privateIPAllocationMethod": "Dynamic",
                    "publicIPAddress": {
                        "id": "/subscriptions/xxxxxxxx-yyyyyy-hghgh-qqwqer/resourceGroups/myResourceGroup/providers/Microsoft.Network/publicIPAddresses/zz-gw-IP-Resource-EastUS2"
                    },
                    "provisioningState": "Succeeded"
                },
                "etag": "W/\"9c8e6845-d88b-4dd1-af96-708c3d55e438\"",
                "type": "Microsoft.Network/virtualNetworkGateways/ipConfigurations",
                "name": "zz-gw-IPConfig-Resource-EastUS2",
                "id": "/subscriptions/xxxxxxxx-yyyyyy-hghgh-qqwqer/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworkGateways/zz-gw-Resource-EastUS2/ipConfigurations/zz-gw-IPConfig-Resource-EastUS2"
            }
        ],
        "resourceGuid": "447f57f0-e5bd-4b1e-ae16-2716a32a542e"
    }
}
Traceback (most recent call last):
  File "../../scripts/az2tf.py", line 337, in <module>
    azurerm_virtual_network_gateway.azurerm_virtual_network_gateway(crf,cde,crg,headers,requests,sub,json,az2tfmess)
  File "/mnt/c/temp/github/py-az2tf-master/scripts/azurerm_virtual_network_gateway.py", line 51, in azurerm_virtual_network_gateway
    sku=azr[i]["properties"]["sku"]["name"]
KeyError: 'sku'
KeyError: 'sku'
Error in az2tf.py
```

**Comment by andyt530** [comment]
posted workaround
